

cc_binary(
    name = "adventOfCode",
    srcs = ["main.cpp", "DataLoader.cpp", "DataLoader.hpp", "SharedAlgorithms.cpp", "SharedAlgorithms.hpp"],
    deps = [],
    copts = ["-D__BUILD_WITH_LOGGER__"],  # Dodaj tę linię
)
